import Head from "next/head";
import Image from "next/image";
import { Montserrat } from "next/font/google";
import styles from "@/styles/Home.module.css";

const montserrat = Montserrat({
	variable: "--font-Montserrat",
	subsets: ["latin"],
});

export default function Home() {
	return (
		<>
			<Head>
				<title>WE Charity - York University</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.png" />
			</Head>
			<div
				className={`${styles.page} ${montserrat.variable}`}
			>
				<div className={styles.container}>
					<div className={styles.col}>
						<div className={styles.banner}>
							<a href="https://www.we.org/en-US/"><img src="/logo.png" width={200}/></a>
						</div>
					</div>
					<div className={styles.col}>
						<div className={styles.donationWrapper}>
							<div className={styles.inner}>
								<h3>Donate to WE Charity <br/> @ <span className={styles.yorku}>York University</span></h3>
								<form className={styles.donationForm} onSubmit={handleSubmit}>
									<img src="/logo_2.png" width={100}/>
									<input type="text" id="name" placeholder="Name" name="name" required />
									<input type="email" id="email" placeholder="Email" name="email" required />
									<input type="number" id="amount" placeholder="Amount (C$)" name="amount" min="0" required />
									<button type="submit">Donate</button>
								</form>
								<br/>
								<p>Thank you for your support! Check out our <a href="https://www.linkedin.com/company/york-free-the-children-chapter/">Linkedin page</a></p>
							</div>
						</div>
					</div>
				</div>
			</div>
		</>
	);

	function handleSubmit(event) {
		event.preventDefault();
		const amount = event.target.amount.value;
		if (amount < 0) {
			alert("Donation amount cannot be negative.");
			return;
		}
		// Handle the form submission logic here
	}
}
